module.exports = {
  content: ['storyblok/**/*.{vue,js}', 'components/**/*.{vue,js}', 'pages/**/*.vue', './layouts/**/*.vue', './nuxt.config.{js,ts}',],
  darkMode: 'class',
  safelist: [
    'bg-primary',
    'bg-secondary',
    'bg-tertiary',
    'bg-medium',
    'bg-dark',
    'bg-white',
    'bg-light',
    'hover:bg-primary',
    'hover:bg-secondary',
    'hover:bg-tertiary',
    'hover:bg-medium',
    'hover:bg-dark',
    'hover:bg-white',
    'hover:bg-light',
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-medium',
    'text-dark',
    'text-white',
    'text-light',
    'hover:text-primary',
    'hover:text-secondary',
    'hover:text-tertiary',
    'hover:text-medium',
    'hover:text-dark',
    'hover:text-white',
    'hover:text-light',
    'border-primary',
    'border-secondary',
    'border-tertiary',
    'border-medium',
    'border-dark',
    'border-white',
    'border-light',
    'items-start',
    'items-center',
    'items-end',
  ],
  theme: {
    fontFamily: {
      sans: 'Roboto, sans-serif',
    },
    extend: {
      colors: {
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        medium: 'var(--medium)',
        light: 'var(--light)',
        dark: 'var(--dark)',
      },
    },
  },
  plugins: [
    require('tailwindcss-animated')
  ],
}